version: "3.7"
services:
  validator-import-launchpad:
    image: sigp/lighthouse:${LIGHTHOUSE_DOCKER_TAG}
    command: lighthouse account validator import --directory /validator_keys
    volumes:
      - /Users/d/ETH2/wallets:/root/.lighthouse
      - /Users/d/ETH2/validator_keys:/validator_keys
