version: "3.7"

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-file: "10"
      max-size: "100m"

services:
  geth:
    image: ethereum/client-go:${GETH_DOCKER_TAG}
    restart: always
    hostname: geth
    command: --goerli --http --http.port=8545 --http.addr=0.0.0.0 --http.vhosts="*" --allow-insecure-unlock --http.api="db,eth,net,web3,personal"
    ports:
      - 30303:30303/tcp
      - 30303:30303/udp
      - 127.0.0.1:8545:8545
    volumes:
      - ./data/geth:/root/.ethereum
    <<: *logging

  beacon:
    image: pegasyseng/teku:${TEKU_DOCKER_TAG}
    restart: always
    hostname: beacon-chain
    depends_on:
      - geth
    command: --config-file=/config/beacon.yaml
    ports:
      - 5051:5051
      - 9001:9001
    volumes:
      - ./data/consensys/teku:/opt/teku/data
      - ./config/teku/beacon.yaml:/config/beacon.yaml:ro
      - ./launchpad:/launchpad
    <<: *logging

  prometheus:
    image: prom/prometheus:v2.21.0
    user: root # https://github.com/prometheus/prometheus/issues/5976
    restart: on-failure
    hostname: prometheus
    command: --storage.tsdb.retention.time=7d --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 127.0.0.1:9094:9090
    volumes:
      - ./config/prometheus/prometheus-t.yaml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus
    <<: *logging

  grafana:
    image: grafana/grafana:7.0.1
    restart: on-failure
    hostname: grafana
    depends_on:
      - prometheus
    ports:
      - 127.0.0.1:3004:3000
    volumes:
      - ./config/grafana/provisioning-t:/etc/grafana/provisioning:ro
      - ./data/grafana:/var/lib/grafana
    <<: *logging

# EOF
